### PR TITLE
upgrade dependency

### PR DESCRIPTION
**Pull request by skyzh**
fix https://github.com/gliderlabs/logspout/issues/449

### CODE REVIEW

**Comment by michaelshobbs** [comment]
looks like the bump in version requires use of a new API

**Comment by skyzh** [comment]
> looks like the bump in version requires use of a new API
> 
> ```
> router/pump.go:160:20: SA1019: p.client.InspectContainer is deprecated: Use InspectContainerWithOptions instead.  (staticcheck)
> 	container, err := p.client.InspectContainer(event.ID)
> 	                  ^
> router/pump.go:206:20: SA1019: p.client.InspectContainer is deprecated: Use InspectContainerWithOptions instead.  (staticcheck)
> 	container, err := p.client.InspectContainer(id)
> 	                  ^
> router/pump.go:273:22: SA1019: p.client.InspectContainer is deprecated: Use InspectContainerWithOptions instead.  (staticcheck)
> 			container, err := p.client.InspectContainer(id)
> ```

In fact I have successfully built and deployed logspout to our server with the `Rate` unmarshal issue solved. I'll look into this.

**Comment by skyzh** [comment]
In fact I have successfully built and deployed logspout to our server with the `Rate` unmarshal issue solved. I'll look into this.

**Comment by michaelshobbs** [comment]
this was caught by `golangci-lint`. the CI process requires this to pass regardless of the code compiling

**Comment by skyzh** [comment]
Thanks for reminding me. I'll fix this soon.

**Comment by skyzh** [comment]
The deprecated API has been removed, according to its implementation here https://github.com/fsouza/go-dockerclient/blob/v1.7.0/container_inspect.go#L14

**Review by michaelshobbs — APPROVED** [review]

**Pull request merged**
