### PR TITLE
Add ONBUILD to build custom modules, fixes #69

### LINKED ISSUE #69: Container build does not compile custom modules
The `RUN` command in the Dockerfile (https://github.com/gliderlabs/logspout/blob/master/Dockerfile#L8) needs to be prefixed with `ONBUILD` to actually run custom module builds. I'll submit a PR that fixes this.

### PR DESCRIPTION
**Pull request by maxpersson**
This should make the custom module functionality work as intended.

### CODE REVIEW

**Comment by progrium** [comment]
This breaks normal logspout though...

**Comment by progrium** [comment]
This is actually more involved than I thought. We also need to keep the source around.

**Comment by progrium** [comment]
https://github.com/gliderlabs/logspout/pull/73

**Comment by maxpersson** [comment]
Will be fixed in #73, closing.

**Pull request closed without merging**
