### PR TITLE
Add optional TCP framing to syslog adapter

### PR DESCRIPTION
**Pull request by michaelshobbs**
closes #429

### CODE REVIEW

**Comment by hhromic** [comment]
Hello!
Thanks for implementing this. There is no documentation at the moment for this new feature, however from the source code I understand that there is now a new `SYSLOG_TCP_FRAMING` environment variable that when set to:

* `traditional` (default) the Syslog message remains unchanged (current behaviour)
* `octet-counted` the Syslog message gets prepended with its octet size (new behaviour)

Is the above correct? If so I could help adding this information to the README file.

Cheers!

**Comment by michaelshobbs** [comment]
That is correct. A `README` PR would be greatly appreciated. 🙏

**Comment by hhromic** [comment]
Done, let me know if you want any changes ;)

**Comment by michaelshobbs** [comment]
#429

**Pull request merged**
