### PR TITLE
Support TLS connections to Docker

### PR DESCRIPTION
**Pull request by josharian**
Respect DOCKER_TLS_VERIFY and DOCKER_CERT_PATH
environment variables. I believe that boot2docker
sets these up by default.

### CODE REVIEW

**Comment by progrium** [comment]
There is nothing wrong with this, but ... you shouldn't run logspout on a different host and if it's on the same host, is TLS necessary?

**Comment by josharian** [comment]
Fair points.

Consider this to be support for development, not production. I bumped into this while playing with logspout. It was easier to add support in logspout than to fight with boot2docker to figure out how to turn off TLS. I suspect I'm not the only one.

**Comment by progrium** [comment]
Oh, so running logspout on os x hitting the boot2docker VM? Did you have a reason not to use the dev container? (`make dev`)

**Comment by josharian** [comment]
Yes, that. No reason, I just didn't notice the dev container.

However:

```bash
$ make dev
flag provided but not defined: -f

Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  --force-rm=false     Always remove intermediate containers, even after unsuccessful builds
  --no-cache=false     Do not use cache when building the image
  -q, --quiet=false    Suppress the verbose output generated by the containers
  --rm=true            Remove intermediate containers after a successful build
  -t, --tag=""         Repository name (and optionally a tag) to be applied to the resulting image in case of success
make: *** [dev] Error 2
```

**Comment by josharian** [comment]
Hmm, maybe I have an old Docker client version. Updating...

**Comment by josharian** [comment]
Updated. `make dev` works.

I think I'd still rather have `go run logspout.go` work, though. Up to you.

**Comment by progrium** [comment]
Try using `make dev` for a bit and let me know if you still think that.

**Comment by josharian** [comment]
Aye aye. Will let this idle and report back. Please consider it abandoned if I've not said anything either way by June 1, 2015. (I may not spend more time on logspout immediately.)

**Comment by inhumantsar** [comment]
+1 to this. Our devs need it for docker-machine.

**Comment by michaelshobbs** [comment]
Closing for now since the use case is dev-related and you can always use `make dev` instead.

**Pull request closed without merging**
