### PR TITLE
Add support for streaming to Kafka.

### PR DESCRIPTION
**Pull request by derekelkins**
sarama is MIT licensed

### CODE REVIEW

**Comment by keithchambers** [comment]
+1

We implemented something similar for a container service for Cisco Cloud:  https://github.com/npateriya/logspout

**Comment by jimmidyson** [comment]
:+1:

**Comment by dylanmei** [comment]
I've also been exploring this.
https://github.com/dylanmei/logspout/tree/kafka_streamer

I wanted to note that Kafka is still maturing. And also Shopify often iterates on their popular go/Kafka api, making breaking changes. Adding any of this into logspout would come with the complexity of accommodating some churn.

**Comment by progrium** [comment]
Do they do tagged releases we could use gopkg.in with?

**Comment by dylanmei** [comment]
No they do not use tagged releases. Reading between the lines of the README they expect us to vendor but don't offer anything more.

https://github.com/Shopify/sarama

Given a little communication, I can't imagine why they wouldn't. It's a solid, hardened library and there's no other Kafka "producer" library for go that I'm aware of.

**Comment by progrium** [comment]
They might believe strongly that vendoring is the Right Way as an excuse to push that responsibility to the user ... which will be interesting with this 3rd party module idea since the kafka module package would have the dependency, not logspout. Yet most vendoring tools are designed for the simple case of the top level project taking care of the vendoring.

**Comment by dylanmei** [comment]
Regarding Kafka/Sarama, the Shopify fellas *are* recommending a godep-style dependency solution while they work towards a "v1". Recently discussed here: https://github.com/Shopify/sarama/issues/342

As for a Kafka producer module for logspout, I'm sitting on one in this fork: https://github.com/dylanmei/logspout/blob/kafka_streamer/router/kafka_streamer.go. This includes a `KAFKA_TEMPLATE`, which is something useful that caught my eye in the "adapters" branch. 

Without yet having route "options", I'm overloading the route `addr` to accept a Kafka topic.

	{
	    "id": "5a1aca62fd9c",
	    "source": {
	        "filter": "spark", "types": ["stdout", "stderr"]
	    },
	    "target": {
	        "type": "kafka", "addr": "kafka-broker1.local:9092,kafka-broker2.local:9020/spark-logs"
	    }
	}

**Comment by eapache** [comment]
Hey folks, just FYI, Sarama has (finally) been tagged with v1.0.0 for use with gopkg.in.

**Comment by progrium** [comment]
Exciting. Also there is a new version of the adapters branch with a PR to master if anybody is interested in looking before it's merged...

**Comment by dylanmei** [comment]
Wow this is great news! @progrium I'll see about adapting to the adapters branch. :+1:

**Comment by progrium** [comment]
Adapters branch is now master.

**Pull request closed without merging**
