### PR TITLE
Allow env vars in stream URLs

### PR DESCRIPTION
**Pull request by jimmidyson**
My personal use case for this is to use Kubernetes service env vars to route logs.

### CODE REVIEW

**Comment by progrium** [comment]
Can you rebase and I can merge this in?

**Comment by jimmidyson** [comment]
Hi @progrium - rebased & works still :)

**Comment by progrium** [comment]
Sorry, rebase again? Major changes just went in. I'll merge quicker this time.

**Comment by jimmidyson** [comment]
Done - still working :)

**Pull request merged**
