### PR TITLE
Allow containers with TTY enabled using environment variable ALLOW_TTY=true

### LINKED ISSUE #231: Missing Logspout logs for containers running with TTY enabled
Just setup a logspout to test it out. Love the ease of use of the tool!

Though I am running into issues with a certain docker-compose v1 template.

```
serviceA:
  image: org/serviceA
  log_driver: 'json-file'
  log_opt:
    max-file: '1'
    max-size: '2M'
```

I noticed in my graylog setup that logspout is not sending any logging details for this service.
When I remove my custom _log_driver_ and _log_opt_ the problem is still not fixed. 

The only way for me to get logspout extracting details from the container of serviceA is when I run it outside of docker-compose.

```
docker run org/serviceA
```

So I am curious as to why some containers in a docker-compose does not get picked up by logspout? Is this a known issue?

### PR DESCRIPTION
**Pull request by michaelshobbs**
pulled this in from @davidnortonjr thanks!

closes #231

### CODE REVIEW

**Comment by davidnortonjr** [comment]
@michaelshobbs did you happen to try this out? Something was bugging me about this last night, and I think I might have never got it working in the end. At my company our platform disallows TTY on services so I don't have day-to-day experience with it.

**Comment by michaelshobbs** [comment]
I'll work on a test today

**Comment by claflico** [comment]
I'm not sure that this is working yet. I'm experimenting with rancher which by default is set to (-i -t) and I can't get it to work unless I change it to "none" in the container config.

**Comment by michaelshobbs** [comment]
>  I can't get it to work unless I change it to "none" in the container config.

@claflico Can you clarify what you mean there?

**Comment by claflico** [comment]
In the rancher web interface, when you launch a new container there are 4 options under "Console". Don't remember the names used at the moment but they are essentially "-t -i", "-i", "-t", & none. Choosing none removes tty: true & stdin_something (sorry) variables from the generated docker-compose.yml file.

**Comment by michaelshobbs** [comment]
@claflico Would you mind opening a new issue on this detail?

**Comment by claflico** [comment]
@michaelshobbs I've actually gone a different route and am using a different logspout container and turned off tty in our containers....i was mostly just commenting to say "me too".

**Comment by josegonzalez** [comment]
@claflico what do you mean by "a different logspout container"?

**Comment by claflico** [comment]
Sorry for the brevity, was on my phone the last two messages.

I switched to a downstream container bekt/logspout-logstash since it already has logstash in it and we already have ELK deployed. 

I'm sure that it still has the same TTY issue as this upstream so for now I just removed "tty: true" and "stdin_open: true" from our docker-compose files as it sounds like they aren't really needed anyways.

**Pull request merged**
